name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system deps (GStreamer + PyGObject)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-gi gir1.2-gstreamer-1.0 libgirepository1.0-dev \
            gstreamer1.0-tools gstreamer1.0-plugins-base gstreamer1.0-plugins-good

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # If a separate test requirements file exists, install it
          if [ -f requirements-test.txt ]; then pip install -r requirements-test.txt; fi

      - name: Lint
        run: |
          python -m pip install flake8
          flake8 || true

      - name: Run tests (if present)
        run: |
          if [ -d tests ]; then \
            python -m pip install pytest pytest-cov; \
            pytest -q --maxfail=1 --disable-warnings; \
          else \
            echo 'No tests directory; skipping.'; \
          fi
